name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-backend:
    name: Build backend image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the backend Docker image
        run: docker build backend/ --tag forum-backend:ci

  build-frontend:
    name: Build frontend image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the frontend Docker image
        run: docker build frontend/ --tag forum-frontend:ci
